SPOTIFY_BASE_ENDPOINT = "https://accounts.spotify.com".freeze
SPOTIFY_EXPORTER_BASE_URL = ENV.fetch('BASE_URL')
CLIENT_ID = ENV.fetch('SPOTIFY_APP_CLIENT_ID')
CLIENT_SECRET = ENV.fetch('SPOTIFY_APP_CLIENT_SECRET')